---
- name: Load variables
  ansible.builtin.include_tasks: load_variables.yml

- name: Run validations
  ansible.builtin.include_tasks: validate.yml

- name: Configure Tailscale node
  ansible.builtin.include_tasks: configure.yml
