---
galaxy_info:
  role_name: deploy
  author: SAPstar
  description: Deploy Tailscale.
  license: MIT
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - tailscale
    - vpn
    - networking
    - linux
dependencies: []
