---
deploy_package_version: null
deploy_pkg_base: "https://pkgs.tailscale.com/stable/{{ 'raspbian' if ssncfg_raspbian | bool else ansible_facts.distribution | lower }}"
deploy_aptkey_url: "{{ deploy_pkg_base }}/{{ ansible_facts.distribution_release }}.noarmor.gpg"
deploy_channel: stable
