# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml

#  _____ _____ _____     _              _____     _                 _
# |   __|  _  |  _  |___| |_ ___ ___   |   | |___| |_ _ _ _ ___ ___| |_
# |__   |     |   __|_ -|  _| .'|  _|  | | | | -_|  _| | | | . |  _| '_|
# |_____|__|__|__|  |___|_| |__,|_|    |_|___|___|_| |_____|___|_| |_,_|
#               SAPstar Network - https://docs.sapstar.eu

# OS dependent variables for Ubuntu Resolute
---
ssncfg_apt_packages:
  - ca-certificates
  - python3-apt
